### ISSUE TITLE
"New group chat" feature doesn't work

### ISSUE THREAD

**Issue by pcowgill** [status-im/status-electron#14]
## Environment
macOS Mojave version 10.14.1

## Description
Clicking Start chat under `New Group chat` doesn't work.

## Steps to Reproduce
After logging in, click `+` button next to `Type here to search chats...`. Then click `Start chat`.

## Expected Behavior
I thought I would be prompted to pick a name for a new public chat.

## Actual Behavior
The app showed nothing but a white screen indefinitely (like how it looks when you first open the desktop app, but it never went away).

**Comment by flexsurfer** [comment]
hey @pcowgill this repo is outdated, please create any issues in https://github.com/status-im/status-react, thank you
